name: Publish Sample Site

on:
  push:
    branches: [ main, dev, web ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Build sample distribution
        run: ./gradlew :jsBrowserDistribution --stacktrace

      - uses: actions/upload-pages-artifact@v3
        if: success()
        with:
          path: build/dist/js/productionExecutable

  deploy:
    needs: build

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
